### ISSUE TITLE
Go live checklist

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/acecentre.org.uk#491]
- [x] Add new subdomain to nginx live site (backend.acecentre.org.uk) 
- [x] Change live wordpress config to use backend.acecentre.org.uk
- [x] Check that the live site redirects to wordpress url
- [x] Update live netlify url to use backend.acecentre.org.uk
- [x] Switch DNS to netlify site
- [x] privacy policy links
- [x] Check subdomains will all be crawled correctly
- [x] Fix emails
- [x] Add redirect from course page to new course page (for emails)
- [x] Update edwiser email `Start enrolling students in courses`
